### ISSUE TITLE
Error after updating tns to 3.4.0

### ISSUE THREAD

**Issue by pascaloo7** [mobilemindtec/nativescript-background-task#10]
Since I updated tns to 3.4.0 `BackgroundTask.postFiles` is giving me an error

`JS: ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'task' of undefined
JS: TypeError: Cannot read property 'task' of undefined
JS:     at createCallback (file:///data/data/nl.salomons.sust/files/app/tns_modules/nativescript-background-task/background-task.js:357:42)
JS:     at Object.exports.postFiles (file:///data/data/nl.salomons.sust/files/app/tns_modules/nativescript-background-task/background-task.js:194:18)`

**Comment by mobilemindtec** [comment]
Hi @pascaloo7,

The code has been fixed and updated. It looks like the way the jar is generated and exposed in the plugin has changed in that version.

**Comment by mobilemindtec** [comment]
https://github.com/NativeScript/NativeScript/issues/5254
